version: '3.9'

volumes:
  docker-data: {}

networks:
  app-network:
    driver: bridge

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - CLEAR_TMP_FOLDER=0
      - DEBUG=${DEBUG:-1}
      - PERSISTENCE=${PERSISTENCE:-1}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR:-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY:-}  # only required for Pro
      - SERVICES=s3,lambda,sns,sqs,iam
      - DATA_DIR=/tmp/localstack/data
      - START_WEB=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_EXECUTION_ENV=True
      - ENV=${NODE_ENV}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-xxxxxxxxx}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-xxxxxxxxxxxxxxxxxxxxx}
      - HOSTNAME_EXTERNAL=localhost
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${VOLUME_DIR_LOCALSTACK:-./docker-data/aws-localstack}:/var/lib/localstack"
      - "${VOLUME_DIR_LOCALSTACK:-./docker-data/aws-localstack}/aws-s3:/tmp/localstack"
      - "${VOLUME_DIR_LOCALSTACK:-./docker-data/aws-localstack}/aws-bootstrap:/opt/bootstrap/"
    networks:
      - app-network

  minio:
    image: minio/minio
    #    command: server --endpoint http://localhost:4572 http://localhost:4572
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
      - MINIO_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-xxxxxxxxx}
      - MINIO_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-xxxxxxxxxxxxxxxxxxxxx}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
      - MINIO_REGION=AWS_REGION
    #      - MINIO_BROWSER=off
    volumes:
      - ./docker-data/localstack/s3:/data
      - ./docker-data/localstack/s3/${AWS_BUCKET_NAME:-my-bucket}:/data"
      - ./docker-data/localstack/${AWS_BUCKET_NAME:-my-bucket}:/data"
    depends_on:
      - localstack