version: '3.9'

volumes:
  docker-data: {}

networks:
  app-network:
    driver: bridge

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      # https://www.innokrea.com/dockerizing-the-frontend-do-it-right-with-react-js-vite
      args:
        - VITE_SERVER_URL=http://localhost:3000
        - VITE_LOCALSTACK_ACCESS_KEY_ID=${LOCALSTACK_ACCESS_KEY_ID:-zzzzzzzzz}
        - VITE_LOCALSTACK_SECRET_ACCESS_KEY=${LOCALSTACK_SECRET_ACCESS_KEY:-zzzzzzzzzzzzzzzzzzzzz}
        - VITE_LOCALSTACK_AWS_REGION=${LOCALSTACK_REGION:-us-east-1}
    ports:
        - "80:80"
    volumes:
        - ./client:/app
        - /app/node_modules
    networks:
        - app-network
    depends_on:
        - server
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - AWS_ACCESS_KEY_ID=${LOCALSTACK_ACCESS_KEY_ID}
      - LOCALSTACK_ACCESS_KEY_ID=${LOCALSTACK_ACCESS_KEY_ID:-zzzzzzzzz}
      - AWS_SECRET_ACCESS_KEY=${LOCALSTACK_SECRET_ACCESS_KEY}
      - LOCALSTACK_SECRET_ACCESS_KEY=${LOCALSTACK_SECRET_ACCESS_KEY:-zzzzzzzzzzzzzzzzzzzzz}
      - AWS_REGION=${LOCALSTACK_REGION}
      - LOCALSTACK_REGION=${LOCALSTACK_REGION:-us-east-1}
      - LOCALSTACK_ENDPOINT=http://localstack:4566  # Use service name, not localhost
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME:-my-bucket}
      - CLIENT_URL=http://localhost:80
      - SERVER_PORT=3000
      - DEBUG=${DEBUG:-1}
    volumes:
      - ./server/src:/app/src
      - ./server/.env.local:/app/.env.local
    networks:
      - app-network
    depends_on:
      - localstack
    restart: unless-stopped

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-aws-utils}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - CLEAR_TMP_FOLDER=0
      - DEBUG=${DEBUG:-1}
      - PERSISTENCE=${PERSISTENCE:-1}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR:-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY:-}
      - SERVICES=s3,lambda,sns,sqs,iam
      - DATA_DIR=/tmp/localstack/data
      - START_WEB=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_EXECUTION_ENV=True
      - ENV=${NODE_ENV}
      - AWS_ACCESS_KEY_ID=${LOCALSTACK_ACCESS_KEY_ID:-zzzzzzzzz}
      - AWS_SECRET_ACCESS_KEY=${LOCALSTACK_SECRET_ACCESS_KEY:-zzzzzzzzzzzzzzzzzzzzz}
      - HOSTNAME_EXTERNAL=localhost
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${VOLUME_DIR_LOCALSTACK:-./docker-data/aws-localstack}:/var/lib/localstack"
      - "${VOLUME_DIR_LOCALSTACK:-./docker-data/aws-localstack}/aws-s3:/tmp/localstack"
      - "${VOLUME_DIR_LOCALSTACK:-./docker-data/aws-localstack}/aws-bootstrap:/opt/bootstrap/"
    networks:
      - app-network